% Combining cavitation data across treatment days for biofilm wounds
% Last updated: 8-01-2025 by Kelly VanTreeck
% DOI: 

% Before running this script, please review the readME and use
% cavitationAnalysis_Step1.m to process the example voltage and time data
% for animals 2 (1700 kPa treatment) and 16 (700 kPa treatment). 

% Analysis summary: This script will process cavitation data generated in
% cavitationAnalysis_Step1 to:
% (1) calculate total cavitation dose across treatment days
% (2) plot net cavitation over time values for each treatment on each day

% Results can be compared to total cavitation dose values in readME and to
% cavitation vs. time plots in supplemental data.

clear all; close all; clc

%% 1) Import cavitation data and set parameters
exportCavData_2 = [];
PBSData_2 = [];
exportCavData_3 = [];
PBSData_3 = [];
exportCavData_4 = [];
PBSData_4 = [];

% Loop through D2, D3, D4
for d = 2:4
    [matfile, matpath] = uigetfile('*.mat', sprintf('Select D%dexampleData_cavDataExport.mat file', d));
    if isequal(matfile, 0)
        error('No file selected for D%d. Exiting loop.', d);
    end

    % Load the file generated by cavitationAnalysis_Step1.m
    data = load(fullfile(matpath, matfile));

    % Rename variables dynamically
    switch d
        case 2
            exportCavData_2 = data.exportCavData;
            PBSData_2 = data.PBSData;
        case 3
            exportCavData_3 = data.exportCavData;
            PBSData_3 = data.PBSData;
        case 4
            exportCavData_4 = data.exportCavData;
            PBSData_4 = data.PBSData;
    end

    fprintf('✅ D%d data loaded and renamed.\n', d);
end

% ——— Parameters ———
vars       = { 'harmonicAUCnet', 'broadbandnet', 'totalcavnet'};
timepoints = [0 15 30 45 60];   % columns
treatments = 1:5;               % rows

%% 2) Day 2
% ----- TOTAL CAVITATION DOSE CALC, day 2 -----
D = exportCavData_2;
animals = unique([D.animalnum]);

% ——— Build results ———
results_2 = struct();

for ai = 1:numel(animals)
  an     = animals(ai);
  recAll = D([D.animalnum]==an);
  pres   = unique([recAll.pressure]);

  % animal‐level fields
  results_2(ai).animalnum = an;
  results_2(ai).pressure  = pres(1);

  % loop variables
  for vi = 1:numel(vars)
    v      = vars{vi};
    rec    = recAll;     % subset for this animal
    nT     = numel(treatments);
    nP     = numel(timepoints);

    % 1) Build rawdata cell (5×5)
    rawdata = cell(nT,nP);
    for ti = treatments
      for pi = 1:nP
        sel = [rec.treatmentnum]==ti & [rec.timepoint]==timepoints(pi);
        if any(sel)
          rawdata{ti,pi} = rec(sel).(v);
        else
          rawdata{ti,pi} = [];
        end
      end
    end

    % 2) meanArray & sdArray (5×5)
    mA  = nan(nT,nP);
    sdA = nan(nT,nP);
    for ti = treatments
      for pi = 1:nP
        vec = rawdata{ti,pi};
        if ~isempty(vec)
          mA(ti,pi)  = mean(vec,'omitnan');
          sdA(ti,pi) = std( vec,'omitnan');
        end
      end
    end

    % 3) Impute missing 0min (col1) or 60min (col5)
    imLog = {};
    for pi = [1 nP]
      missingRows = find(isnan(mA(:,pi)));
      for ri = missingRows'
        others = setdiff(treatments, ri);
        mA(ri,pi)  = mean( mA(others,pi),  'omitnan');
        sdA(ri,pi) = mean( sdA(others,pi), 'omitnan');
        imLog{end+1} = sprintf(...
          'Animal %d: imputed tp=%d for treat %d (var=%s)',...
          an, timepoints(pi), ri, v);
      end
    end

    % 4) Per‐treatment AUC & AUC_SD
    T = struct('treatment',cell(1,nT),...
               'AUC',       cell(1,nT),...
               'AUC_SD',    cell(1,nT));
    for ti = treatments
      y = mA(ti,:);
      s = sdA(ti,:);
      valid = ~isnan(y);
      xRow  = timepoints(valid);
      yRow  = y(valid);
      sRow  = s(valid);

      % trapezoidal segments
      dx     = diff(xRow);
      area   = dx .* (yRow(1:end-1)+yRow(2:end))/2;
      varSeg = ((dx/2).^2) .* ( sRow(1:end-1).^2 + sRow(2:end).^2 ); %segment variance formula

      T(ti).treatment = ti;
      T(ti).AUC       = sum(area,       'omitnan');
      T(ti).AUC_SD    = sqrt(sum(varSeg,'omitnan'));
    end

    % 5) Total across treatments
    allAUCs   = [T.AUC];
    allAUCSDs = [T.AUC_SD];
    totAUC    = sum(allAUCs,   'omitnan');
    totAUC_SD = sqrt(sum(allAUCSDs.^2,'omitnan'));

    % 6) Assemble varStruct
    varStruct.rawdata      = rawdata;
    varStruct.meanArray    = mA;
    varStruct.sdArray      = sdA;
    varStruct.imputeLog    = imLog;
    varStruct.treatment    = T;
    varStruct.totalAUC     = totAUC;
    varStruct.totalAUC_SD  = totAUC_SD;

    % insert into results
    results_2(ai).(v) = varStruct;
  end
end

% Build imputedMask for each animal and variable
for ai = 1:numel(results_2)
    for vi = 1:numel(vars)
        v = vars{vi};
        imLog = results_2(ai).(v).imputeLog;
        mask = false(nT, nP);  % initialize

        for i = 1:numel(imLog)
            logEntry = imLog{i};
            % Extract timepoint and treatment from the log string
            tokens = regexp(logEntry, 'tp=(\d+).*treat (\d+)', 'tokens');
            if ~isempty(tokens)
                tp = str2double(tokens{1}{1});
                tr = str2double(tokens{1}{2});
                pi = find(timepoints == tp);
                ti = find(treatments == tr);
                if ~isempty(pi) && ~isempty(ti)
                    mask(ti, pi) = true;
                end
            end
        end

        % Store the mask in the results structure
        results_2(ai).(v).imputedMask = mask;
    end
end

% ---- CAVITATION OVER TIME, day 2 ----
% Plots cavitation dose vs. time for comparison to supplemental figures for
    % provided animals
for ai = 1:numel(results_2)
    figure;
    tiledlayout(5,1); % 5 rows, 1 column

    % Extract metadata
    animalnum = results_2(ai).animalnum;
    pressure = results_2(ai).pressure;

    % Extract data arrays
    harmonicMean  = results_2(ai).harmonicAUCnet.meanArray;
    harmonicSD    = results_2(ai).harmonicAUCnet.sdArray;

    broadbandMean = results_2(ai).broadbandnet.meanArray;
    broadbandSD   = results_2(ai).broadbandnet.sdArray;

    totalMean     = results_2(ai).totalcavnet.meanArray;
    totalSD       = results_2(ai).totalcavnet.sdArray;

    for ti = 1:5
        nexttile;
    
        % Get masks for this treatment row
        harmonicMask  = ~results_2(ai).harmonicAUCnet.imputedMask(ti, :);
        broadbandMask = ~results_2(ai).broadbandnet.imputedMask(ti, :);
        totalMask     = ~results_2(ai).totalcavnet.imputedMask(ti, :);
    
        % Filter timepoints and values
        xH = timepoints(harmonicMask);
        yH = results_2(ai).harmonicAUCnet.meanArray(ti, harmonicMask);
        eH = results_2(ai).harmonicAUCnet.sdArray(ti, harmonicMask);
    
        xB = timepoints(broadbandMask);
        yB = results_2(ai).broadbandnet.meanArray(ti, broadbandMask);
        eB = results_2(ai).broadbandnet.sdArray(ti, broadbandMask);
    
        xT = timepoints(totalMask);
        yT = results_2(ai).totalcavnet.meanArray(ti, totalMask);
        eT = results_2(ai).totalcavnet.sdArray(ti, totalMask);
    
        % Plot each line with error bars
        errorbar(xH, yH, eH, '-o', 'DisplayName', 'Harmonic'); hold on;
        errorbar(xB, yB, eB, '-s', 'DisplayName', 'Broadband');
        errorbar(xT, yT, eT, '-^', 'DisplayName', 'Total Cavitation');
    
        ylabel(['Treatment ' num2str(ti)]);
        grid on;
    
        if ti == 1
            legend('Location', 'best');
        end
        if ti == 5
            xlabel('Time (min)');
        end
    end

    sgtitle(['Day 2: Animal ' num2str(animalnum) ' | Gent/PA + ' num2str(pressure) ' kPa']);
end


%% Day 3
% ----- TOTAL CAVITATION DOSE CALC, day 3 -----
D = exportCavData_3;
animals = unique([D.animalnum]);

% ——— Build results ———
results_3 = struct();

for ai = 1:numel(animals)
  an     = animals(ai);
  recAll = D([D.animalnum]==an);
  pres   = unique([recAll.pressure]);

  % animal‐level fields
  results_3(ai).animalnum = an;
  results_3(ai).pressure  = pres(1);

  % loop variables
  for vi = 1:numel(vars)
    v      = vars{vi};
    rec    = recAll;     % subset for this animal
    nT     = numel(treatments);
    nP     = numel(timepoints);

    % 1) Build rawdata cell (5×5)
    rawdata = cell(nT,nP);
    for ti = treatments
      for pi = 1:nP
        sel = [rec.treatmentnum]==ti & [rec.timepoint]==timepoints(pi);
        if any(sel)
          rawdata{ti,pi} = rec(sel).(v);
        else
          rawdata{ti,pi} = [];
        end
      end
    end

    % 2) meanArray & sdArray (5×5)
    mA  = nan(nT,nP);
    sdA = nan(nT,nP);
    for ti = treatments
      for pi = 1:nP
        vec = rawdata{ti,pi};
        if ~isempty(vec)
          mA(ti,pi)  = mean(vec,'omitnan');
          sdA(ti,pi) = std( vec,'omitnan');
        end
      end
    end

    % 3) Impute missing 0min (col1) or 60min (col5)
    imLog = {};
    for pi = [1 nP]
      missingRows = find(isnan(mA(:,pi)));
      for ri = missingRows'
        others = setdiff(treatments, ri);
        mA(ri,pi)  = mean( mA(others,pi),  'omitnan');
        sdA(ri,pi) = mean( sdA(others,pi), 'omitnan');
        imLog{end+1} = sprintf(...
          'Animal %d: imputed tp=%d for treat %d (var=%s)',...
          an, timepoints(pi), ri, v);
      end
    end

    % 4) Per‐treatment AUC & AUC_SD
    T = struct('treatment',cell(1,nT),...
               'AUC',       cell(1,nT),...
               'AUC_SD',    cell(1,nT));
    for ti = treatments
      y = mA(ti,:);
      s = sdA(ti,:);
      valid = ~isnan(y);
      xRow  = timepoints(valid);
      yRow  = y(valid);
      sRow  = s(valid);

      % trapezoidal segments
      dx     = diff(xRow);
      area   = dx .* (yRow(1:end-1)+yRow(2:end))/2;
      varSeg = ((dx/2).^2) .* ( sRow(1:end-1).^2 + sRow(2:end).^2 ); %segment variance formula

      T(ti).treatment = ti;
      T(ti).AUC       = sum(area,       'omitnan');
      T(ti).AUC_SD    = sqrt(sum(varSeg,'omitnan'));
    end

    % 5) Total across treatments
    allAUCs   = [T.AUC];
    allAUCSDs = [T.AUC_SD];
    totAUC    = sum(allAUCs,   'omitnan');
    totAUC_SD = sqrt(sum(allAUCSDs.^2,'omitnan'));

    % 6) Assemble varStruct
    varStruct.rawdata      = rawdata;
    varStruct.meanArray    = mA;
    varStruct.sdArray      = sdA;
    varStruct.imputeLog    = imLog;
    varStruct.treatment    = T;
    varStruct.totalAUC     = totAUC;
    varStruct.totalAUC_SD  = totAUC_SD;

    % insert into results
    results_3(ai).(v) = varStruct;
  end
end

% ---- CAVITATION OVER TIME, day 3 ----
for ai = 1:numel(results_3)
    figure;
    tiledlayout(5,1); % 5 rows, 1 column

    % Extract metadata
    animalnum = results_3(ai).animalnum;
    pressure = results_3(ai).pressure;

    % Extract data arrays
    harmonicMean  = results_3(ai).harmonicAUCnet.meanArray;
    harmonicSD    = results_3(ai).harmonicAUCnet.sdArray;

    broadbandMean = results_3(ai).broadbandnet.meanArray;
    broadbandSD   = results_3(ai).broadbandnet.sdArray;

    totalMean     = results_3(ai).totalcavnet.meanArray;
    totalSD       = results_3(ai).totalcavnet.sdArray;

    for ti = 1:5
        nexttile;
    
        % Get masks for this treatment row
        harmonicMask  = ~results_3(ai).harmonicAUCnet.imputedMask(ti, :);
        broadbandMask = ~results_3(ai).broadbandnet.imputedMask(ti, :);
        totalMask     = ~results_3(ai).totalcavnet.imputedMask(ti, :);
    
        % Filter timepoints and values
        xH = timepoints(harmonicMask);
        yH = results_3(ai).harmonicAUCnet.meanArray(ti, harmonicMask);
        eH = results_3(ai).harmonicAUCnet.sdArray(ti, harmonicMask);
    
        xB = timepoints(broadbandMask);
        yB = results_3(ai).broadbandnet.meanArray(ti, broadbandMask);
        eB = results_3(ai).broadbandnet.sdArray(ti, broadbandMask);
    
        xT = timepoints(totalMask);
        yT = results_3(ai).totalcavnet.meanArray(ti, totalMask);
        eT = results_3(ai).totalcavnet.sdArray(ti, totalMask);
    
        % Plot each line with error bars
        errorbar(xH, yH, eH, '-o', 'DisplayName', 'Harmonic'); hold on;
        errorbar(xB, yB, eB, '-s', 'DisplayName', 'Broadband');
        errorbar(xT, yT, eT, '-^', 'DisplayName', 'Total Cavitation');
    
        ylabel(['Treatment ' num2str(ti)]);
        grid on;
    
        if ti == 1
            legend('Location', 'best');
        end
        if ti == 5
            xlabel('Time (min)');
        end
    end

    sgtitle(['Day 3: Animal ' num2str(animalnum) ' | Gent/PA + ' num2str(pressure) ' kPa']);
end

%% Day 4
% ---- TOTAL CAVITATION DOSE, day 4 ----
D = exportCavData_4;
animals = unique([D.animalnum]);

% ——— Build results ———
results_4 = struct();

for ai = 1:numel(animals)
  an     = animals(ai);
  recAll = D([D.animalnum]==an);
  pres   = unique([recAll.pressure]);

  % animal‐level fields
  results_4(ai).animalnum = an;
  results_4(ai).pressure  = pres(1);

  % loop variables
  for vi = 1:numel(vars)
    v      = vars{vi};
    rec    = recAll;     % subset for this animal
    nT     = numel(treatments);
    nP     = numel(timepoints);

    % 1) Build rawdata cell (5×5)
    rawdata = cell(nT,nP);
    for ti = treatments
      for pi = 1:nP
        sel = [rec.treatmentnum]==ti & [rec.timepoint]==timepoints(pi);
        if any(sel)
          rawdata{ti,pi} = rec(sel).(v);
        else
          rawdata{ti,pi} = [];
        end
      end
    end

    % 2) meanArray & sdArray (5×5)
    mA  = nan(nT,nP);
    sdA = nan(nT,nP);
    for ti = treatments
      for pi = 1:nP
        vec = rawdata{ti,pi};
        if ~isempty(vec)
          mA(ti,pi)  = mean(vec,'omitnan');
          sdA(ti,pi) = std( vec,'omitnan');
        end
      end
    end

    % 3) Impute missing 0min (col1) or 60min (col5)
    imLog = {};
    for pi = [1 nP]
      missingRows = find(isnan(mA(:,pi)));
      for ri = missingRows'
        others = setdiff(treatments, ri);
        mA(ri,pi)  = mean( mA(others,pi),  'omitnan');
        sdA(ri,pi) = mean( sdA(others,pi), 'omitnan');
        imLog{end+1} = sprintf(...
          'Animal %d: imputed tp=%d for treat %d (var=%s)',...
          an, timepoints(pi), ri, v);
      end
    end

    % 4) Per‐treatment AUC & AUC_SD
    T = struct('treatment',cell(1,nT),...
               'AUC',       cell(1,nT),...
               'AUC_SD',    cell(1,nT));
    for ti = treatments
      y = mA(ti,:);
      s = sdA(ti,:);
      valid = ~isnan(y);
      xRow  = timepoints(valid);
      yRow  = y(valid);
      sRow  = s(valid);

      % trapezoidal segments
      dx     = diff(xRow);
      area   = dx .* (yRow(1:end-1)+yRow(2:end))/2;
      varSeg = ((dx/2).^2) .* ( sRow(1:end-1).^2 + sRow(2:end).^2 ); %segment variance formula

      T(ti).treatment = ti;
      T(ti).AUC       = sum(area,       'omitnan');
      T(ti).AUC_SD    = sqrt(sum(varSeg,'omitnan'));
    end

    % 5) Total across treatments
    allAUCs   = [T.AUC];
    allAUCSDs = [T.AUC_SD];
    totAUC    = sum(allAUCs,   'omitnan');
    totAUC_SD = sqrt(sum(allAUCSDs.^2,'omitnan'));

    % 6) Assemble varStruct
    varStruct.rawdata      = rawdata;
    varStruct.meanArray    = mA;
    varStruct.sdArray      = sdA;
    varStruct.imputeLog    = imLog;
    varStruct.treatment    = T;
    varStruct.totalAUC     = totAUC;
    varStruct.totalAUC_SD  = totAUC_SD;

    % insert into results
    results_4(ai).(v) = varStruct;
  end
end

% Build imputedMask for each animal and variable
for ai = 1:numel(results_4)
    for vi = 1:numel(vars)
        v = vars{vi};
        imLog = results_4(ai).(v).imputeLog;
        mask = false(nT, nP);  % initialize

        for i = 1:numel(imLog)
            logEntry = imLog{i};
            % Extract timepoint and treatment from the log string
            tokens = regexp(logEntry, 'tp=(\d+).*treat (\d+)', 'tokens');
            if ~isempty(tokens)
                tp = str2double(tokens{1}{1});
                tr = str2double(tokens{1}{2});
                pi = find(timepoints == tp);
                ti = find(treatments == tr);
                if ~isempty(pi) && ~isempty(ti)
                    mask(ti, pi) = true;
                end
            end
        end

        % Store the mask in the results structure
        results_4(ai).(v).imputedMask = mask;
    end
end

% ---- CAVITATION OVER TIME, day 4 ----
for ai = 1:numel(results_4)
    figure;
    tiledlayout(5,1); % 5 rows, 1 column

    % Extract metadata
    animalnum = results_4(ai).animalnum;
    pressure = results_4(ai).pressure;

    % Extract data arrays
    harmonicMean  = results_4(ai).harmonicAUCnet.meanArray;
    harmonicSD    = results_4(ai).harmonicAUCnet.sdArray;

    broadbandMean = results_4(ai).broadbandnet.meanArray;
    broadbandSD   = results_4(ai).broadbandnet.sdArray;

    totalMean     = results_4(ai).totalcavnet.meanArray;
    totalSD       = results_4(ai).totalcavnet.sdArray;

    for ti = 1:5
        nexttile;
    
        % Get masks for this treatment row
        harmonicMask  = ~results_4(ai).harmonicAUCnet.imputedMask(ti, :);
        broadbandMask = ~results_4(ai).broadbandnet.imputedMask(ti, :);
        totalMask     = ~results_4(ai).totalcavnet.imputedMask(ti, :);
    
        % Filter timepoints and values
        xH = timepoints(harmonicMask);
        yH = results_4(ai).harmonicAUCnet.meanArray(ti, harmonicMask);
        eH = results_4(ai).harmonicAUCnet.sdArray(ti, harmonicMask);
    
        xB = timepoints(broadbandMask);
        yB = results_4(ai).broadbandnet.meanArray(ti, broadbandMask);
        eB = results_4(ai).broadbandnet.sdArray(ti, broadbandMask);
    
        xT = timepoints(totalMask);
        yT = results_4(ai).totalcavnet.meanArray(ti, totalMask);
        eT = results_4(ai).totalcavnet.sdArray(ti, totalMask);
    
        % Plot each line with error bars
        errorbar(xH, yH, eH, '-o', 'DisplayName', 'Harmonic'); hold on;
        errorbar(xB, yB, eB, '-s', 'DisplayName', 'Broadband');
        errorbar(xT, yT, eT, '-^', 'DisplayName', 'Total Cavitation');
    
        ylabel(['Treatment ' num2str(ti)]);
        grid on;
    
        if ti == 1
            legend('Location', 'best');
        end
        if ti == 5
            xlabel('Time (min)');
        end
    end

    sgtitle(['Day 4: Animal ' num2str(animalnum) ' | Gent/PA + ' num2str(pressure) ' kPa']);
end

%% TOTAL CAV DOSE, all days
% Combining results across days for "total cav dose"
% ——— Variables & Setup ———
nVar    = numel(vars);
nAnimals = numel(results_2);

% Build variable names and types for the summary table
colNames   = ["PressureAnimal"];
colTypes   = ["string"];
for iV = 1:nVar
  v = vars{iV};
  colNames(end+1:end+2) = [v+"_TotalAUC", v+"_TotalAUC_SD"];
  colTypes(end+1:end+2) = ["double","double"];
end

% Preallocate table
T_summary = table('Size',[nAnimals,1+2*nVar], ...
                  'VariableTypes',colTypes, ...
                  'VariableNames',colNames);

% ——— Fill in each row ———
for i = 1:nAnimals
  % assume same animalnum & pressure in each results_N
  an   = results_2(i).animalnum;
  pres = results_2(i).pressure;
  
  % 1) PressureAnimal string
  T_summary.PressureAnimal(i) = sprintf("%d_%d", pres, an);
  
  % 2) Loop variables
  for j = 1:nVar
    v = vars{j};
    
    % pull the three days
    A1 = results_2(i).(v).totalAUC;
    A2 = results_3(i).(v).totalAUC;
    A3 = results_4(i).(v).totalAUC;
    
    S1 = results_2(i).(v).totalAUC_SD;
    S2 = results_3(i).(v).totalAUC_SD;
    S3 = results_4(i).(v).totalAUC_SD;
    
    % sum of AUCs
    sumAUC  = sum([A1, A2, A3],'omitnan');
    % propagate SD: sqrt(Σ sd_i^2)
    sumVar  = S1.^2 + S2.^2 + S3.^2;
    sumSD   = sqrt(sumVar);
    
    % assign into table
    T_summary{i, v+"_TotalAUC"}    = sumAUC;
    T_summary{i, v+"_TotalAUC_SD"} = sumSD;
  end
end

T_summary = sortrows(T_summary, 'PressureAnimal', 'ascend');
disp(T_summary) %check here that T_summary matches values in readME